### ISSUE TITLE
Unable to negotiate with 127.0.0.1 port 57416: no matching key exchange method found. Their offer: diffie-hellman-group14-sha1,diffie-hellman-group1-sha1 [preauth]

### ISSUE THREAD

**Issue by stephen-smith** [qterm/qterm#28]
"QTerm 0.7.3 (Qr 5.11.1 based)" fails to connect to: "OpenSSH_8.3p1 Debian-1, OpenSSL 1.1.1d  10 Sep 2019"

**Comment by hephooey** [comment]
I only implemented diffie-hellman-group14-sha1 and diffie-hellman-group1-sha1 for ssh2 key exchange. QTerm is not a general purpose ssh client, you should not use it if security is a concern. Otherwise you can edit the KexAlgorithms term in sshd_config to allow diffie-hellman-group14-sha1 for example.

**Comment by xiaoqiangwang** [comment]
Add "diffie-hellman-group14-sha256" in QTerm 0.8.0.
